### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by jpmeijers** [RAKWireless/RAKwireless-Arduino-BSP-Index#3]
We've had this problem before. It was fixed, but seems like it's back again after updating the BSP to the one in the repo.

```
Sketch uses 123776 bytes (15%) of program storage space. Maximum is 815104 bytes.
Global variables use 15356 bytes (6%) of dynamic memory, leaving 222212 bytes for local variables. Maximum is 237568 bytes.
Upgrading target on /dev/ttyACM0 with DFU package /tmp/arduino_build_754762/RAK4631-DeepSleep-LoRaWan.ino.zip. Flow control is disabled, Single bank, Touch disabled
###############################Timed out waiting for acknowledgement from device.

Failed to upgrade target. Error is: No data received on serial port. Not able to proceed.
Traceback (most recent call last):
  File "/home/jpmeijers/.local/lib/python3.8/site-packages/nordicsemi/__main__.py", line 294, in serial
    dfu.dfu_send_images()
  File "/home/jpmeijers/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu.py", line 235, in dfu_send_images
    self._dfu_send_image(HexType.APPLICATION, self.manifest.application)
  File "/home/jpmeijers/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu.py", line 206, in _dfu_send_image
    self.dfu_transport.send_firmware(firmware)
  File "/home/jpmeijers/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 213, in send_firmware
    self.send_packet(pkt)
  File "/home/jpmeijers/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 243, in send_packet
    ack = self.get_ack_nr()
  File "/home/jpmeijers/.local/lib/python3.8/site-packages/nordicsemi/dfu/dfu_transport_serial.py", line 282, in get_ack_nr
    raise NordicSemiException("No data received on serial port. Not able to proceed.")
nordicsemi.exceptions.NordicSemiException: No data received on serial port. Not able to proceed.

Possible causes:
- Selected Bootloader version does not match the one on Bluefruit device.
    Please upgrade the Bootloader or select correct version in Tools->Bootloader.
- Baud rate must be 115200, Flow control must be off.
- Target is not in DFU mode. Ground DFU pin and RESET and release both to enter DFU mode.
```

**Comment by jpmeijers** [comment]
It might be a bootloader issue as described on the forum:

https://forum.rakwireless.com/t/wisblock-rak4630-upload-fails-intermittently/3923

https://forum.rakwireless.com/t/updated-bootloader-for-rak4631/3952

**Comment by jpmeijers** [comment]
Updating bootloader definitely helps.
